name: SpoutShops
author: Richard Lang
email: langricr@bell.net
version: 1.1
main: org.ss.SpoutShopPlugin
depend: [Vault]

permissions:
    spoutshops.*:
        default: op
        description: Gives all SpoutShops permissions.
        children:
            spoutshops.admin: true
            spoutshops.create.*: true
            spoutshops.destroy: true
            spoutshops.interact: true
    spoutshops.admin:
        default: op
        description: Permits the modification and destruction of others' shops.
    spoutshops.create.*:
        default: true
        description: Permits the creation of all shop types.
        children:
            spoutshops.create.sign: true
    spoutshops.create.sign:
        default: true
        description: Permits the creation of sign-based shops.
    spoutshops.interact.*:
        default: op
        description: Allows players to interact with all spoutshop interfaces.
        children:
            spoutshops.interact.sign: true
    spoutshops.interact.sign:
        default: true
        description: Allows the player to interact with Sign-based spoutshops.
    spoutshops.destroy:
        default: true
        description: Permits the destruction of owned shops.