name: SpoutShops
author: Richard Lang
email: langricr@bell.net
version: 1.08
main: org.ss.SpoutShopPlugin
depend: [Vault,Spout]
softdepend: [PermissionsEx]

permissions:
    spoutshops.*:
        default: op
        description: Gives all SpoutShops permissions.
        children:
            spoutshops.admin: true
            spoutshops.create: true
            spoutshops.destroy: true
            spoutshops.interact: true
    spoutshops.admin:
        default: op
        description: Permits the modification and destruction of others' shops.
    spoutshops.create:
        default: true
        description: Permits the creation of shops.
    spoutshops.interact:
        default: op
        description: Allows players to interact with all spoutshop interfaces.
    spoutshops.destroy:
        default: true
        description: Permits the destruction of owned shops.